version: 1.0.{build}
    platform:
      - x64

    install:
      - cmd: echo "Downloading conan..."
      - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
      - cmd: pip.exe install conan
      - cmd: conan user # Create the conan data directory
      - cmd: conan --version

    build_script:
      - cmd: mkdir build
      - cmd: conan install . oatpp/1.0.0@ -o oatpp:shared=True
      - cmd: cd build
      - cmd: cmake ../ -G "Visual Studio 14 2015 Win64"
      - cmd: cmake --build . --config Release

    test_script:
      - cmd: cd bin
      - cmd: test_package.exe
