build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "oatpp/1.0.0"
    CONAN_USERNAME: "user"
    CONAN_LOGIN_USERNAME: "user"
    CONAN_CHANNEL: "channel"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3.exe install conan --upgrade
  - pip3.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe build.py"
